calc_pages/views.py
from flask import render_template, request, Blueprint
from calc_pages.forms import OptConstForm
from calc_pages.models import Compound, Density
from calc_pages.x_ray_mirrors.plotters import OptConstPlotter


calc = Blueprint('calc', __name__, url_prefix='/calc')


@calc.route('/beta-delta', methods=["POST", "GET"])
def beta_delta():
    plotter = OptConstPlotter()

    # download all available elements and compounds from the databases
    choices_comp = [(c.formula, f'{c.formula} ({c.density:.1f} г/см3)') for c in Compound.query
                    .join(Density, onclause=Compound.id == Density.compound_id)
                    .add_columns(Compound.formula, Density.density)
                    .filter((Density.density.isnot(None)) & (~Compound.formula.contains('∙'))
                                                          & (~Compound.formula.contains('(')))
                    .order_by(Compound.formula)
                    .all()]

    opt_const_form = OptConstForm()
    opt_const_form.materials.choices = choices_comp

    if request.method == "POST":
        energy = float(request.form.get('energy'))
        compounds = request.form.getlist('materials')
        graph = plotter.plot_opt_consts(compounds, energy)
    else:
        graph = plotter.plot_opt_consts([], 100)

    return render_template("calculations/beta_delta.html", title="Оптические константы", opt_const_form=opt_const_form,
                           plot=graph)


@calc.route('/mlm-parameters', methods=["POST", "GET"])
def mlm_parameters():
    return render_template("calculations/mlm_parameters.html", title="Оптимальные параметры зеркал")

routes.py
from flask import render_template, redirect, url_for, request, jsonify, Blueprint
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash

import config
from plugins import db
from site_models import User, Method, Employee, Conference, Publications
from xray_models import Element, Compound
from forms import OptConstForm


main_bp = Blueprint('main', __name__, url_prefix='')


@main_bp.route('/')
def home_page():
    data_conferences = db.session.query(Conference).all()
    return render_template("index.html", title="ЛУМРС", data_conferences=data_conferences)


@main_bp.route('/employees')
def peoples():
    data_employees = {'professor': [], 'work_horse': [], 'student': []}
    data = db.session.query(Employee).all()

    for employee in data:
        data_employees[employee.label].append(employee)

    return render_template("employees.html", title="Состав лаборатории", data_employees=data_employees)


@main_bp.route('/publications')
def publications():
    data_publications = {}
    data = db.session.query(Publications).all()

    publications_num = len(data)

    for publication in data:
        if publication.year not in data_publications:
            data_publications[publication.year] = []
        data_publications[publication.year].append(publication)

    return render_template("publications.html", title="Публикации", data_publications=data_publications,
                           publications_num=publications_num)


@main_bp.route('/research')
def research():
    return render_template("research.html", title="Направления исследований")


@main_bp.route('/methods')
def methods():
    data = db.session.query(Method).all()
    return render_template("methods.html", title="Методы исследований", data_methods=data)


@main_bp.route('/contacts')
def contacts():
    return render_template("contacts.html", title="Контакты")


@main_bp.route('/research-materials')
def gallery():
    return render_template("research_materials.html", title="Материалы")


@main_bp.route('/history')
def history():
    return render_template("history.html", title="История лаборатории")


@main_bp.route('/beta-delta', methods=["POST", "GET"])
def beta_delta():
    if request.method == 'POST':
        return

    # download all available elements and compounds from the databases
    choices_el = [(e.Element, e.Element) for e in Element.query.all()]
    choices_comp = [(c.formula, c.formula) for c in Compound.query.all()]

    opt_const_form = OptConstForm()
    opt_const_form.materials.choices = choices_el + choices_comp

    return render_template("beta_delta.html", title="Оптические константы", opt_const_form=opt_const_form)


@main_bp.route('/login', methods=["POST", "GET"])
def login():
    if request.method == 'POST':
        user = User.query.filter_by(name=request.form['username']).first()
        if user and check_password_hash(user.password, request.form['password']):
            login_user(user)
            return jsonify('success')
    return jsonify('No-data')


@main_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home_page'))

templates/beta_delta.html
{% include "header.html" %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@2.0.1/dist/css/multi-select-tag.css">
<script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@2.0.1/dist/js/multi-select-tag.js"></script>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<section id="Materials">

    <div class="materials-box">
        <div class="row mt-5 px-4">
            <div class="col-3 select-materials-and-energy">
                <form method="POST" name="calc_form" class="mt-5">
                    {{ opt_const_form.materials.label() }}
                    {{ opt_const_form.materials(id="materials") }}

                    {{ opt_const_form.energy.label(class="mt-2") }}
                    {{ opt_const_form.energy(class="energy") }}

                    {{ opt_const_form.submit(class="mt-4 btn btn-warning") }}
                </form>
            </div>
            <div class="col-9 chart" id="opt_const_graph">
                <script>
                    var graphs = {{plot | safe}};
                    Plotly.plot('opt_const_graph',graphs,{});
                </script>
            </div>

        </div>
    </div>

</section>

<script>
    new MultiSelectTag('materials', {
    rounded: true,    // default true
    shadow: true,      // default false
    placeholder: 'Search',  // default Search...
    tagColor: {
        textColor: '#327b2c',
        borderColor: '#92e681',
        bgColor: '#eaffe6',
    },
    onChange: function(values) {
        console.log(values)
    }
    })
</script>


{% include "footer.html" %}

templates/contacts.html
{% include "header.html" %}

<section id="Contacts">

    <div class="research-box">

        <h2 class="text-center">Наши контакты</h2>
        <hr class="my-4">

        <div class="row">

            <div class="col-lg-4 gy-3">
                <h4 class="mb-4">Почтовый адрес</h4>
                <p class="mb-4">198504<br>
                    Санкт-Петербург, Ульяновская ул., д. 1<br>
                    Кафедра Электроники Твердого Тела<br>
                    Лаборатория Ультрамягкой Рентгеновской Спектроскопии</p>
                <a class="mail-ref" href="mailto:xraylab.spbu@gmail.com"><i class="fas fa-envelope-square"></i>&nbsp xraylab.spbu@gmail.com</a>
            </div>

            <div class="col-lg-8 gy-3">
                <iframe class="float-end mb-5" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28329.30381884725!2d29.817080072677307!3d59.885466826067045!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696413a07b1d28f%3A0x494135ef1f8d4cb6!2z0YPQuy4g0KPQu9GM0Y_QvdC-0LLRgdC60LDRjywgMSwg0KHQsNC90LrRgi3Qn9C10YLQtdGA0LHRg9GA0LMsIDE5ODUwNA!5e0!3m2!1sru!2sru!4v1619547253236!5m2!1sru!2sru" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>


        </div>


    </div>

</section>

{% include "footer.html" %}

templates/employees.html
{% include "header.html" %}


<!--Main content-->
<section id="Content">
    <div class="container-fluid">

        <h1 class="text-center">Состав научной группы</h1>
            {% set label_desc = {'professor': 'Профессора', 'work_horse': 'Рабочие лошадки', 'student': 'Студенты'} %}

            <!--Persons by rang-->
            {% for label in data_employees %}
                <div class="employee-type-row row mt-5 mb-1 mx-0 pt-2 pb-1 px-3">
                <h2>{{ label_desc[label] }}</h2>
                </div>

                <div class="row">
                {% for employee in data_employees[label] %}
                    <div class="col-lg-3 col-md-6 col-sm-1 gy-4">
                        <div class="card employee-card">

                            {# Photo #}
                            <div class="card-header employee-card-header">
                                <div class="profile-img-box">
                                    <img src="{{ url_for('static', filename='img/{}'.format(employee.img)) }}" alt="profile image" class="img-fluid card-img-top">
                                </div>
                            </div>

                            {# Main info #}
                            <div class="card-body px-4 employee-card-body">

                                {# Name, degree, position #}
                                <div class="name-in-card">
                                    <h4 class="card-title mb-2">{{ employee.name }}</h4>
                                    {% if employee.degree %}
                                        <h6 class="card-subtitle text-secondary">{{ employee.degree }}</h6>
                                    {% endif %}
                                    {% if employee.position %}
                                        <h6 class="card-subtitle text-secondary">{{ employee.position }}</h6>
                                    {% endif %}
                                </div>

                                {# Phone and email #}
                                <p class="card-text">
                                    {% if employee.phone %}
                                        <i class="fas fa-phone"></i>&nbsp&nbsp{{ employee.phone }}<br>
                                    {% endif %}
                                    {% if employee.email %}
                                        <a class="mail-ref" href="mailto:{{ employee.email }}"><i class="fas fa-envelope-square"></i>&nbsp&nbsp{{ employee.email }}</a><br>
                                    {% endif %}
                                </p>

                            </div>

                            {# Links to science resources #}
                            <div class="card-footer employee-card-footer d-flex justify-content-center align-items-center">
                                <p class="card-text">
                                    {% if employee.rg %}
                                        <a href="{{ employee.rg }}"><span class="iconify r-gate" data-icon="simple-icons:researchgate" data-inline="false"></span></a>
                                    {% endif %}
                                    {% if employee.sc %}
                                        <a href="{{ employee.sc }}"><span class="iconify scopus" data-icon="simple-icons:scopus" data-inline="false"></span></a>
                                    {% endif %}
                                    {% if employee.publons %}
                                        <a href="{{ employee.publons }}"><img class="publons" src="{{ url_for('static', filename='icons/clarivate.svg') }}"></img></a>
                                    {% endif %}
                                    {% if employee.orcid %}
                                        <a href="{{ employee.orcid  }}"><span class="iconify orcid" data-icon="cib:orcid" data-inline="false"></span></a>
                                    {% endif %}
                                </p>
                            </div>

                        </div>
                    </div>
                {% endfor %}
                </div>
            {% endfor %}

    </div>
</section>

{% include "footer.html" %}

templates/footer.html
<footer class="container-fluid mx-auto mt-5 d-flex justify-content-center">
    <p>© 2024 Лаборатория Ультрамягкой рентгеновской спектроскопии</p>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script>
    $(document).ready(function(){
      {# Clicking #login_button after pressing Enter #}
      $('#password').keypress(function(e){
        if(e.keyCode === 13)
        $('#login_button').click();
      });

      $("#signIn").on('hide.bs.modal', function (e) {
          $("#wrongEmail:visible").hide();
          $("#bothFieldsRequired").hide();
          $("#username").val('');
          $("#password:visible").val('');
      });

      {# Link bootstrap modal and /login route #}
      $('#login_button').click(function(){
           var username = $('#username').val();
           var password = $('#password').val();
           var wrongEmail = $('#wrongEmail');
           var bothFieldsRequired = $('#bothFieldsRequired');

           if (wrongEmail.is(':visible')){
               wrongEmail.hide();
           }

           if (bothFieldsRequired.is(':visible')){
               bothFieldsRequired.hide();
           }

           if(username !== '' && password !== '')
           {
                $.ajax({
                     url:"/login",
                     method:"POST",
                     data: {username:username, password:password},
                     success:function(data)
                     {
                          if(data === 'No-data')
                          {
                              wrongEmail.show();
                          }
                          else
                          {
                               $('#signIn').hide();
                               window.location.replace('/admin')
                          }
                     }
                });
           }
           else
           {
                bothFieldsRequired.show();
           }
      });
    });
</script>

</body>

</html>

templates/gallery.html
{% include "header.html" %}

<section id="Gallery">

</section>

{% include "footer.html" %}

templates/header.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <!--Favicon-->
    <link rel="icon" href="{{ url_for('static', filename='icons/x-ray_icon.png') }}">

    <!--Bootstrap CSS and JS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <!--Custom css-->
    <link href="../static/css/styles.css" rel="stylesheet">

    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/e0bbca903f.js" crossorigin="anonymous"></script>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>

</head>

<body>

<section id="Title">

    <!--Navigation bar-->
    <header class="navbar navbar-expand-lg navbar-dark bd-gutter bg-primary fixed-top">

        <nav class="container-fluid">

            <!-- Button trigger popup with sign in -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#signIn">
              <i class="fas fa-door-open"></i>
            </button>

            <!--Button in case of collapse-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!--Pages-->
            <div class="navbar-collapse collapse justify-content-end" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('main.home_page') }}"><i class="fas fa-home"></i></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Группа</a>
                        <ul class="dropdown-menu rounded-1">
                            <li><a class="dropdown-item" href="{{ url_for('main.peoples') }}">Состав</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('main.publications') }}">Публикации</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.research') }}">Исследования</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.methods') }}">Методы</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.history') }}">История</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.gallery') }}">Материалы</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.contacts') }}">Контакты</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Popup with sign in form -->
    {% include "containers/sign_in_popup.html" %}


</section>

templates/index.html
{% include "header.html" %}

    <!--Main content-->
    <section id="Content">

        <!-- Main content images -->
        <div id="carouselMainPage" class="container-fluid carousel slide" data-bs-ride="carousel">

          <div class="carousel-indicators">
              {% for img in index_images %}
                {% if loop.index == 1 %}
                   <button type="button" data-bs-target="#carouselMainPage" data-bs-slide-to="{{ loop.index - 1 }}"
                           class="active" aria-current="true" aria-label="Slide {{ loop.index }}"></button>
                {% else %}
                   <button type="button" data-bs-target="#carouselMainPage" data-bs-slide-to="{{ loop.index - 1 }}"
                           aria-label="Slide {{ loop.index }}"></button>
                {% endif %}

              {% endfor %}
          </div>

          <div class="carousel-inner main-content-image-box">
              {% for img in index_images %}
                {% if loop.index == 1 %}
                   {% set active = ' active' %}
                {% else %}
                   {% set active = '' %}
                {% endif %}

                <div class="carousel-item main-content-image-box{{ active }}" data-bs-interval="5000">
                  <img src="{{ img }}" class="img-fluid main-content-image" alt="{{ img.split('/')[-1] }}">
                </div>

              {% endfor %}
          </div>

        </div>

        <div class="container-fluid">
            <div class="row">

                <!-- Conferences and schools -->
                <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h3>Конференции и школы</h3>
                        </div>
                        <div class="card-body">
                            {% for conference in data_conferences %}
                                <div class="pb-3">
                                    <a href="{{ conference.url }}">
                                        <p class="card-text lead mb-0">{{ conference.title }}</p>
                                        {% if conference.deadline %}
                                            <small class="text-muted">Регистрация до: {{ conference.deadline.date() }}</small>
                                            <br>
                                        {% endif %}
                                        <small class="text-muted">Дата проведения: {{ conference.dates }}</small>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="col-lg-8 col-md-8 col-sm-12 mb-3">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h3>Новости</h3>
                        </div>
                        <div class="card-body">
                            <p class="card-text">Здесь когда-нибудь будут новости</p>
                            <small class="text-muted">Дата публикации</small>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% include "footer.html" %}

templates/methods.html
{% include "header.html" %}

<section id="Methods" class="container-fluid">

    <h2 class="text-center">Основные методы исследований</h2>
    <hr class="my-4">

    <div class="row">
        {% for method in data_methods %}

            <!-- Method block -->
            <div class="col-12 gy-2">
                <div class="card method-card p-4">
                    <div class="row">

                        <!-- Image -->
                        <div class="col-4">
                            <div class="method-img-box rounded">
                                <img src="{{ url_for('static', filename='img/methods/{}'.format(method.img)) }}" alt="xps">
                            </div>
                        </div>

                        <!-- Description -->
                        <div class="col-8">
                            <h3 class="mb-3 px-4 py-2 rounded bg-primary text-white">{{ method.title }}</h3>
                              {% for text_block in method.description.split('<br>') %}
                                <p class="px-4 py-2 rounded bg-light">{{ text_block }}</p>
                              {% endfor %}
                        </div>

                    </div>
                </div>
            </div>

        {% endfor %}
    </div>

</section>

{% include "footer.html" %}

templates/publications.html
{% include 'header.html' %}

<section>
    <div class="container-fluid">
        <h2 class="text-center">Публикации</h2>

        {% set count = namespace(value=publications_num) %}
        {% for pub_year in data_publications %}
            <div class="row px-5 mt-5 mb-4">
                <div class="publication-year px-3 py-1">
                        <h3 class="m-0 fw-bold">{{ pub_year }}</h3>
                </div>
            </div>


                {% for publication in data_publications[pub_year] %}
                    <div class="row px-5 mt-3">

                    <!-- TOC image -->
                    <div class="toc-image-box col px-4 d-flex flex-wrap align-items-center d-none d-lg-block">
                        {% if publication.toc_image %}
                            {% set file = publication.toc_image %}
                        {% else %}
                            {% set file = 'placeholder2.jpg' %}
                        {% endif %}
                        <img src="{{ url_for('static', filename='img/publications/{}'.format(file)) }}" alt="{{ file }}" class="img-fluid">
                    </div>

                    <!-- Publication card -->
                    <div class="card publication-card px-0 rounded-0 border-0 col-lg-9">
                        <div class="card-header publication-card-header rounded-0 border-0">
                            <p class="m-0 fw-bold">{{ publication.title }}</p>
                        </div>
                        <div class="card-body publication-card-body bg-light pt-2">
                            <div class="row">
                                <div class="col">
                                    <p class="m-0 fs-6">{{ publication.authors }}</p>
                                    <p class="fst-italic mt-1"><b>{{ publication.journal }}</b>,
                                        {% if publication.volume %}
                                         Volume {{ publication.volume }},
                                        {% endif %}
                                        {% if publication.issue %}
                                         Issue {{ publication.issue }},
                                        {% endif %}
                                        {% if publication.pages %}
                                         pp. {{ publication.pages }}
                                        {% endif %}
                                    </p>
                                </div>
                                <div class="col-1 d-flex align-items-center flex-column mt-auto">
                                    <div class="numberCircle">{{ count.value }}</div>
                                    {% set count.value = count.value - 1 %}
                                </div>
                            </div>
                        </div>
                        <!-- DOI -->
                        <a href="{{ publication.doi }}" class="stretched-link"></a>
                    </div>


            </div>
            {% endfor %}
            {% endfor %}

{#        <div class="row px-5 mt-3">#}
{#            <div class="col">#}
{#                <img src="{{ url_for('static', filename='img/publications/gaisin2024.png') }}" alt="gaisin2024" class="img-fluid">#}
{#            </div>#}
{#            <div class="card publication-card px-0 rounded-0 border-0 col-lg-9">#}
{#                <div class="card-header publication-card-header rounded-0 border-0">#}
{#                    <p class="m-0 fw-bold">Effect of low-temperature oxidation and heat treatment under vacuum on the Al–Be interdiffusion process</p>#}
{#                </div>#}
{#                <div class="card-body bg-light pt-2">#}
{#                    <p class="m-0">A. U. Gaisin, E. O. Filatova</p>#}
{#                    <p class="m-0 fst-italic mt-1">Physical Chemistry Chemical Physics, Volume 26, Issue 2, pp. 780</p>#}
{#                </div>#}
{#                <a href="https://doi.org/10.1039/D3CP04309F" class="stretched-link"></a>#}
{#            </div>#}
{#        </div>#}
    </div>

</section>

{% include 'footer.html' %}

templates/research_materials.html
{% include "header.html" %}

<section id="Materials" class="container-fluid">

    <div class="materials-box mt-3">

        <div class="row d-flex flex-wrap">

            <div class="col-md-6 col-sm-12 p-2">
                <div class="card">
                    <div class="card-header text-center">
                        <h5>Расчеты оптических констант</h5>
                    </div>
                    <div class="card-body d-flex justify-content-center">
                        $$n=1-\delta-i\beta=1-\left(\frac{N_a r_e \lambda^2}{2\pi}\right)(f_1+if_2)$$
                    </div>
                    <a href="{{ url_for('calc.beta_delta') }}" class="stretched-link"></a>
                </div>
            </div>

            <div class="col-md-6 col-sm-12 p-2">
                <div class="card">
                    <div class="card-header text-center">
                        <h5>Расчеты оптимальных параметров зеркал</h5>
                    </div>
                    <div class="card-body d-flex justify-content-center align-middle">
                        <img src="{{ url_for('static', filename='img/research_methods/mlm.png') }}" alt="optical constants" class="img-fluid">
                    </div>
                    <a href="{{  url_for('calc.mlm_parameters') }}" class="stretched-link"></a>
                </div>
            </div>

        </div>

    </div>

</section>

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

{% include "footer.html" %}